# Generated by Django 3.0.5 on 2020-04-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_titel', models.CharField(max_length=1000)),
                ('post_banner_image', models.ImageField(upload_to='mainblog/static/media')),
                ('post_content', models.TextField()),
            ],
        ),
    ]
