# Generated by Django 3.0.5 on 2020-04-20 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainblog.Blog_Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_banner_image',
            field=models.ImageField(upload_to='mainblog/static/mainblog/media'),
        ),
    ]
