# Generated by Django 3.0.5 on 2020-04-20 03:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0003_auto_20200419_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_comment_allows',
            field=models.BooleanField(default=True, verbose_name='Is Comment Allow'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
