# Generated by Django 3.0.5 on 2020-04-20 04:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0004_auto_20200419_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=1000)),
                ('massage', ckeditor.fields.RichTextField()),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Is Contacted')),
            ],
        ),
        migrations.CreateModel(
            name='Extrapages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=300)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Websiteuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
