# Generated by Django 3.0.5 on 2020-04-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0006_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrapages',
            name='slug',
            field=models.CharField(default='', max_length=200),
        ),
    ]
